### ISSUE TITLE
Unable to load DLL 'OpenPoseDotNetNative'

### ISSUE THREAD

**Issue by bruce987** [takuya-takeuchi/OpenPoseDotNet#12]
Hi takuya-takeuchi,

I have been able to build and run the original OpenPose C++ on my new laptop. I have since been trying to get the OpenPoseDotNet to work. I have taken some code from one of the examples, built it, but when I run it I get the dreaded "Unable to load DLL" or one if its dependencies. I located a "Dependencies" tool and loaded the DLL into it. Here's the link for the tool https://lucasg.github.io/Dependencies/ The old depends.exe does not work. So I'm seeing some DLL's that I don't have on my system... '**api-ms-win-core-wow64-11-1-1.dll**'...and others. Since I've been communicating with you, I've been seeing this problem, but thought I was not building correctly.

My research indicates that these DLL's have been eliminated in Windows 10, but I don't understand why it builds! I'm still researching. 

I assume you are using **Windows 10 1909** release? All my systems are on this release.

![image](https://user-images.githubusercontent.com/1581231/78192617-1fe33600-743e-11ea-8023-c346de8da03c.png)

The dependencies view...
![image](https://user-images.githubusercontent.com/1581231/78192696-3f7a5e80-743e-11ea-9a8f-8ad6ac3ffa3d.png)

Thanks,
Bruce

**Comment by bruce987** [comment]
I have no clue why this error is happening. I'm trying to take some code from one of the examples and load it into my .NET application using your library. Basically I'm trying to do what OpenPose demos does (the one from CMU labs).

**Comment by takuya-takeuchi** [comment]
@bruce987 
Very sorry late reply. We world are just focusing to beat threat of COVID-19. Thank you for your patient.

> I assume you are using Windows 10 1909 release? All my systems are on this release.

Yes. My dev machine is latest windows.

The following is result of dependencies for OpenPoseDotNet.Native.dll.

![image](https://user-images.githubusercontent.com/6241854/79033996-b5748780-7bed-11ea-8b8d-3de9606527d2.png)

But there is no dependency issue.
This weird issues is reported in https://github.com/lucasg/Dependencies/issues/102

If you can, you can upload your build OpenPoseDotNet.Native.dll and I can check dependencies and work on my machine.

Thanks.

**Comment by bruce987** [comment]
@takuya-takeuchi 

Yes I'm on Windows 10 1909 release. My investigation indicates that the *-wow-* dll's are no longer installed on Windows latest release, which I verify is accurate.
I had to change the extension to txt, dll is not supported download type.
[OpenPoseDotNetNative.dll.txt](https://github.com/takuya-takeuchi/OpenPoseDotNet/files/4465265/OpenPoseDotNetNative.dll.txt)

**Comment by takuya-takeuchi** [comment]
@bruce987 
This is your built library.

![スクリーンショット 2020-04-12 11 34 43](https://user-images.githubusercontent.com/6241854/79059141-b5d65680-7cb1-11ea-9a0a-3d30dfc0e1eb.png)

However, there is no issue.
Uhh.. My dev machine is not installed as clear install.
It may mean that -wow- dll's remains from old version windows.
So I should create new 1909 machine as Hyper-V and test it.

**Comment by bruce987** [comment]
If you open the first link and drill down you might see an error. The interesting thing is the OpenPose library shows the same issue, but runs without issue... that’s what has me baffled!

**Comment by bruce987** [comment]
@takuya-takeuchi ,

Since I was able to load and run your 'examples\TutorialApiCpp\01_BodyFromImageDefault'; I took that build libraries and put them into my application that I'm building. This runs basically without issues.

...but I have another question which I will open a new issue.
-Bruce
