### ISSUE TITLE
Question about 1_ThreadUserProcessingFunction

### ISSUE THREAD

**Issue by sota1994** [takuya-takeuchi/OpenPoseDotNet#23]
Hi,
Am I supposed to implement image processing (draw keypoints skeleton) in WUserClass? The program just shows plain video stream from camera. I also cant find any code that implements and uses opwrapper in this tutorial.
I hope to hear back from you soon.
Thank you,
Dung Tran

**Comment by takuya-takeuchi** [comment]
@sota1994 
Yes.Current code has not code to draw keypoints.
We have to implement **renderKeypointsCpu** from https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/src/openpose/utilities/keypoint.cpp

However, I'm not sure we can use Datum.PoseKeyPoints to draw keypoints.

**Comment by sota1994** [comment]
I see. Thank you for your help!
