### ISSUE TITLE
Not work with RTX 2080ti GPU

### ISSUE THREAD

**Issue by bydaniel** [takuya-takeuchi/OpenPoseDotNet#8]
HI,

I thank you for your effort on this. This wrapper is very useful.

By the way, I've recently upgraded my GPU to Geforce RTX 2080Ti, but I couldn't run the library, which worked fine on the previous graphic card. I found that this issue was resolved in the lastest OpenPose version. 

Do you have any plan to update the library to use the latest OpenPose? Thank you in advance.

**Comment by takuya-takeuchi** [comment]
Recently, I didn’t check openpose code.
So I need time to catch up openpose code.

BTW, could you tell me revision openpose supports latest gpu?

**Comment by bydaniel** [comment]
Thank you for the quick response!

I'm using the latest one, "20d8eca" revision for OpenPose. They say this new version has a faster and more accurate tracking capability than before. I'm looking forward to your update! Very excited!

**Comment by takuya-takeuchi** [comment]
@bydaniel 
thanks.
I found the openpose issue.
https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1290

And revision is https://github.com/CMU-Perceptual-Computing-Lab/openpose/commit/559a57ec436f28ebdc29b2d27d5d075604fd1239

Ops, 129 commits behind openpose master. hahaha

**Comment by bydaniel** [comment]
I'm glad you found the issue on OpenPose.

So, how long do you think it'll take for you to apply the new OpenPose for this OpenPoseDotNet?

**Comment by takuya-takeuchi** [comment]
@bydaniel 
I caught up latest revision. on 3bda13acca9b41fc79033d75af91763b94b05e1f.
Please build on develop branch and have a try.

And please close this issue if it works on RTX 2080Ti.

**Comment by bydaniel** [comment]
Thanks Takuya,

I will give it a try on the latest version and let you know how it goes. Thanks for your help!

Daniel

**Comment by bydaniel** [comment]
I have compiled the latest version, but I failed to run. When I run OpenPoseDemo, it gives me an exception of "Unable to load DLL 'OpenPoseDotNetNative': The specified module could not be found. (Exception from HRESULT: 0x8007007E)". 

Also, I don't know why the output file of the OpenPoseDemo project is the OpenPoseDemo.dll, not an executable file. 

Any suggestions?

**Comment by takuya-takeuchi** [comment]
@bydaniel 
Did you use CopyOpenPoseOnlyNative.bat?
It includes wrong command.
You may need to correct it.

And this sample is .net core app.
So output binary does not have .exe.

**Comment by bydaniel** [comment]
I found the source of the problem. As you mentioned, there were some typos in CopyOpenPoseXX.bat files. After I manually copied all the dlls, it runs correctly. 

Thank you so much for your help. Really appreciated.
